spring:
  data:
    mongodb:
      authentication-database: admin
      username: user
      password: pass
      database: url_compact
      port: 27017
      host: localhost
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      password: "mysecretpassword"